### ISSUE TITLE
How to advertise library's regular community meetings?

### ISSUE THREAD

**Issue by TomNicholas** [scientific-python/learn.scientific-python.org#46]
Hi, I'd like to advertise [xarray's recurring public dev calls](https://github.com/pydata/xarray/issues/4001) on the scientific python website, but it's not clear to me where they should go. Is there a collective calendar somewhere?

**Comment by jarrodmillman** [comment]
https://scientific-python.org/calendars/

**Comment by jarrodmillman** [comment]
Here is an example PR: https://github.com/scientific-python/scientific-python.org/pull/266
